#ifndef DUNGEON_GAME_TILETYPES_H
#define DUNGEON_GAME_TILETYPES_H

enum ETileType
{
    ETILETYPE_VOID,
    ETILETYPE_GRANITE,
    ETILETYPE_STONEWALL,
    ETILETYPE_STONEFLOOR,
    ETILETYPE_COUNT
};

#endif
