/// AUTOGENERATED VERSION.H - DO NOT MODIFY
///  - To change these values, please modify the project's root CMakeLists.txt
#ifndef __APPLICATION_VERSION_H__
#define __APPLICATION_VERSION_H__
#include <string>
 
/**
 * Stores this application's version and build strings
 */
namespace Version
{
    const std::string TITLE      = "Dungeon Crawler";
    const std::string AUTHOR     = "Scott MacDonald";
    const std::string EMAIL      = "scott@whitespaceconsideredharmful.com";
    const std::string WEBSITE    = "";
    const std::string COPYRIGHT  = "Copyright (c) 2012 Scott MacDonald";
    const std::string VERSION_S  = "0.1.2-development";
    const std::string RELEASE    = "development";
    const std::string REVISION   = "c7329901060a57da3b4a8dcfbd53ff250fd2d183";
    const std::string COMPILER   = "gcc4.4.3";
}
 
#endif
