/// AUTOGENERATED VERSION.H - DO NOT MODIFY
///  (Generated by scripts/versioning.h)
#ifndef APPLICATION_VERSION_H
#define APPLICATION_VERSION_H
#include <string>
 
namespace Version
{
    const std::string TITLE      = "Dungeon Crawl";
    const std::string AUTHOR     = "Scott MacDonald";
    const std::string EMAIL      = "scott@whitespaceconsideredharmful.com";
    const std::string WEBSITE    = "http://www.whitespaceconsideredharmful.com";
    const std::string COPYRIGHT  = "Copyright (c) 2010 Scott MacDonald";
    const std::string VERSION_S  = "0.1.1-development";
    const std::string RELEASE    = "development";
    const std::string REVISION   = "7d5e3db59adb8092b948ce1e2fd8c37d1afdd950
";
    const std::string BUILDREV_S = "7d5e3db59adb8092b948ce1e2fd8c37d1afdd950
 (uncomitted changes)";
    const std::string BUILD_DATE = "2011-12-15 14:50";
}
 
#endif
